server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: expense-tracker-backend
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: expensetracker_user
    password: expensetracker_password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf8
          useUnicode: true
  
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# OCR Configuration
ocr:
  tesseract:
    data-path: /usr/share/tessdata
    language: eng
    confidence-threshold: 60.0

# File Upload Configuration
file:
  upload:
    max-size: 10MB
    allowed-types: jpg,jpeg,png,pdf
    storage-path: ./uploads

# Logging Configuration
logging:
  level:
    com.expensetracker: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true 